### PR TITLE
[WIP] Server side render

### PR DESCRIPTION
**Pull request by shanedg**
Work to address #32 

Implementation of steps outlined in this guide [here](https://medium.com/bucharestjs/upgrading-a-create-react-app-project-to-a-ssr-code-splitting-setup-9da57df2040a)

Almost works at this point but presence of BrowserRouter within App crashes the server:
`Invariant Violation: Browser history needs a DOM`

Research [here](https://reacttraining.com/react-router/web/guides/server-rendering) on rendering routes separately at server. Probably need to break App out such that it can be wrapped by either Router instance.

Not 100% pleased with the less-than-current usage of babel in the above guide. In particular, `babel-preset-es2015` isn't the recommended way to go anymore and I needed to force `babel-preset-react-app` to v3.1.1 to squelch babel version mismatch errors.  Would want to upgrade to latest babel practices if router issues are sorted.

There's also more work to do to deploy the server such that it serves routes on my domain, as well as readying [express for production](https://expressjs.com/en/advanced/best-practice-performance.html).

### CODE REVIEW

**Comment by shaneboy** [comment]
Hi Shane--it's Shane! FYI create react app has upgraded to latest babel in recent release: https://reactjs.org/blog/2018/10/01/create-react-app-v2.html

Migrating to latest CRA version might solve some of the above babel issues.

**Comment by shanedg** [comment]
Abandoned some of the specifics of the above guide to leverage latest babel behavior version. Still have outstanding issue around `BrowserRouter` on the server side but feel more comfortable proceeding here.

**Comment by shanedg** [comment]
Latest naively relies on near-identical version of `<App />`, `<ServerSideApp />`, which implements `StaticRouter as Router` instead of `BrowserRouter as Router`.

Unfortunately, does not yet correctly render `import`ed image in `<Header />` component, because webpack is the mechanism actually grabbing the correct source.

**Comment by shanedg** [comment]
Pulled `Router` component out of `App` logic, wrapping in client and server contexts with appropriate router; made cloned `ServerSideApp` unnecessary.

**Comment by shanedg** [comment]
Tested deployment on Amazon Fargate using docker image uploaded to AWS ECR. Need to ready express app for production; in particular, need to sort out `PORT` things before I can test on a staging subdomain.

**Comment by shanedg** [comment]
Moving work to #73, resolved merge conflicts from `develop` there.

**Pull request closed without merging**
